name: Setup Node & pnpm
description: Install the requested Node.js version, enable Corepack, prepare the desired pnpm version, then (optionally) run `pnpm install`.

inputs:
  node-version:
    description: Node.js version (e.g. 20.x / 22.x)
    required: true
  pnpm-version:
    description: pnpm version to activate with Corepack
    required: false
    default: 10.11.1
  run-install:
    description: 'If "true", run: pnpm install --frozen-lockfile'
    required: false
    default: "true"

runs:
  using: composite
  steps:
    # 1) Node (with pnpm cache)
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs['node-version'] }}
        cache: pnpm

    # 2) Enable + prepare the exact pnpm version via Corepack
    - name: Prepare pnpm
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@${{ inputs['pnpm-version'] }} --activate
        pnpm --version

    # 3) Optional dependency install
    - name: Install dependencies
      if: inputs.run-install == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
