# --------------------------------------------------------------------------- #
#  🔄  Release preparation ( preview → main "handoff" branch)                  #
# --------------------------------------------------------------------------- #
name: 🔄 Release Preparation

# Fires whenever code is pushed to the preview branch (the pre‑release branch)
on:
  push:
    branches: [preview]

# We need to update files and push a commit
permissions:
  contents: write
  pull-requests: read

# --------------------------------------------------------------------------- #
#  Main preparation job                                                       #
# --------------------------------------------------------------------------- #
jobs:
  prepare:
    name: 🔄 Release Preparation
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # --------------------------------------------------------------------- #
      # 1️⃣  Repo + tooling                                                   #
      # --------------------------------------------------------------------- #
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛠️ Setup Node & pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: 22.x

      # --------------------------------------------------------------------- #
      # 2️⃣  Identify version bump (semver heuristic)                         #
      # --------------------------------------------------------------------- #
      - name: 🏷️ Last released tag
        id: last_tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)" >> "$GITHUB_OUTPUT"

      - name: 📝 Collect commits since last tag
        id: commits
        run: |
          RANGE="${{ steps.last_tag.outputs.tag }}..HEAD"
          COMMITS=$(git log "$RANGE" --max-count=200 --pretty=format:'%h %s%n%b')
          {
            echo 'commits<<EOF'
            echo "$COMMITS"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: 🔍 Determine semver bump type
        id: bump
        env:
          RAW: ${{ steps.commits.outputs.commits }}
        run: |
          echo "$RAW" > _c.txt
          if grep -Eq '(^|[\n])BREAKING CHANGE:|!:' _c.txt; then
            echo 'type=major' >> "$GITHUB_OUTPUT"
          elif grep -Eq '^[a-f0-9]+ feat(\(|:)' _c.txt; then
            echo 'type=minor' >> "$GITHUB_OUTPUT"
          else
            echo 'type=patch' >> "$GITHUB_OUTPUT"
          fi
          rm _c.txt

      # --------------------------------------------------------------------- #
      # 3️⃣  Bump package.json (no git tag yet)                               #
      # --------------------------------------------------------------------- #
      - name: 📈 Bump version
        id: version
        run: |
          NEW=$(npm version ${{ steps.bump.outputs.type }} --no-git-tag-version)
          echo "version=${NEW#v}" >> "$GITHUB_OUTPUT"

      # --------------------------------------------------------------------- #
      # 4️⃣  Prepare variables for OpenAI prompt                              #
      # --------------------------------------------------------------------- #
      - name: 📝 Prepare changelog variables
        id: vars
        run: |
          # Save commits to temporary file to handle multi-line content safely
          cat > commits_temp.txt <<'EOF'
          ${{ steps.commits.outputs.commits }}
          EOF

          # Read commits and escape for simple KEY=VALUE format
          COMMITS_ESCAPED=$(cat commits_temp.txt | tr '\n' '\020' | sed 's/"/\\"/g')

          # Create variables in a single line format for safe GitHub Actions passing
          TEMPLATE_VARS="VERSION=${{ steps.version.outputs.version }}
          COMMITS=${COMMITS_ESCAPED}
          DATE=$(date +%Y-%m-%d)"

          # Encode the entire vars block as base64 to avoid shell parsing issues
          VARS_ENCODED=$(echo "$TEMPLATE_VARS" | base64 -w 0)

          # Output for GitHub Actions as a single line
          echo "template_vars=${VARS_ENCODED}" >> "$GITHUB_OUTPUT"

          # Clean up
          rm -f commits_temp.txt

      # --------------------------------------------------------------------- #
      # 5️⃣  Generate CHANGELOG entry with structured OpenAI output            #
      # --------------------------------------------------------------------- #
      - name: 🤖 Generate changelog entry
        id: changelog
        uses: ./.github/actions/openai-chat
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          system-path: .github/prompts/changelog.sys.md
          template-path: .github/prompts/changelog.user.md
          schema-path: .github/schema/changelog.schema.json
          output-path: .github/outputs/changelog.output.md
          vars: ${{ steps.vars.outputs.template_vars }}
          model: ${{ secrets.OPENAI_MODEL || 'gpt-4o-mini' }}
          temperature: 0.3
          max-tokens: 1200

      # --------------------------------------------------------------------- #
      # 6️⃣  Write / prepend the new entry to CHANGELOG.md                    #
      # --------------------------------------------------------------------- #
      - name: 📝 Update CHANGELOG.md
        run: |
          VER=${{ steps.version.outputs.version }}
          TODAY=$(date +%Y-%m-%d)

          # Use formatted content if available, otherwise fall back to raw content
          if [ -n "${{ steps.changelog.outputs.formatted_content }}" ]; then
            CHANGELOG_CONTENT="${{ steps.changelog.outputs.formatted_content }}"
          else
            CHANGELOG_CONTENT="${{ steps.changelog.outputs.content }}"
          fi

          # The formatted output already includes the ## [version] - date header
          # So we can use it directly, just add a separator
          ENTRY="$CHANGELOG_CONTENT\n\n---\n"

          { head -n 9 CHANGELOG.md; echo -e "$ENTRY"; tail -n +10 CHANGELOG.md; } > CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md

      # --------------------------------------------------------------------- #
      # 7️⃣  Commit & push                                                    #
      # --------------------------------------------------------------------- #
      - name: 💾 Commit version + changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git add package.json CHANGELOG.md
          git commit -m "chore(release): v${{ steps.version.outputs.version }} – update changelog" \
            || echo "Nothing to commit"
          git push

      # --------------------------------------------------------------------- #
      # 8️⃣  Summary                                                          #
      # --------------------------------------------------------------------- #
      - name: 🎉 Release prep summary
        run: |
          {
            echo "## 🎉 Release Preparation Complete"
            echo ""
            echo "- **Version:**  `${{ steps.version.outputs.version }}`"
            echo "- **Bump type:** `${{ steps.bump.outputs.type }}`"
            echo "- **CHANGELOG:** updated and committed"
            echo ""
            echo "➡️  Create a PR from **preview ➡️ main** when ready to publish."
          } >> "$GITHUB_STEP_SUMMARY"
