# --------------------------------------------------------------------------- #
#  🔄  Release preparation ( preview → main "handoff" branch)                  #
# --------------------------------------------------------------------------- #
name: 🔄 Release Preparation

# Fires whenever code is pushed to the preview branch (the pre‑release branch)
on:
  push:
    branches: [preview]

# We need to update files and push a commit
permissions:
  contents: write
  pull-requests: read

# --------------------------------------------------------------------------- #
#  Main preparation job                                                       #
# --------------------------------------------------------------------------- #
jobs:
  prepare:
    name: 🔄 Release Preparation
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # --------------------------------------------------------------------- #
      # 1️⃣  Repo + tooling                                                   #
      # --------------------------------------------------------------------- #
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛠️ Setup Node & pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: 22.x

      # --------------------------------------------------------------------- #
      # 2️⃣  Identify version bump (semver heuristic)                         #
      # --------------------------------------------------------------------- #
      - name: 🏷️ Last released tag
        id: last_tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)" >> "$GITHUB_OUTPUT"

      - name: 📝 Collect commits since last tag
        id: commits
        run: |
          RANGE="${{ steps.last_tag.outputs.tag }}..HEAD"
          COMMITS=$(git log "$RANGE" --max-count=200 --pretty=format:'%h %s%n%b')
          {
            echo 'commits<<EOF'
            echo "$COMMITS"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: 🔍 Determine semver bump type
        id: bump
        env:
          RAW: ${{ steps.commits.outputs.commits }}
        run: |
          BUMP_TYPE=$(./.github/scripts/release-prepare/determine-semver-bump.sh)
          echo "$BUMP_TYPE" >> "$GITHUB_OUTPUT"

      # --------------------------------------------------------------------- #
      # 3️⃣  Bump package.json (no git tag yet)                               #
      # --------------------------------------------------------------------- #
      - name: 📈 Bump version
        id: version
        run: |
          NEW=$(npm version ${{ steps.bump.outputs.type }} --no-git-tag-version)
          echo "version=${NEW#v}" >> "$GITHUB_OUTPUT"

      # --------------------------------------------------------------------- #
      # 4️⃣  Prepare variables for OpenAI prompt                              #
      # --------------------------------------------------------------------- #
      - name: 📝 Prepare changelog variables
        id: vars
        env:
          VERSION: ${{ steps.version.outputs.version }}
          COMMITS_INPUT: ${{ steps.commits.outputs.commits }}
        run: |
          VARS_OUTPUT=$(./.github/scripts/release-prepare/prepare-openai-vars.sh)
          echo "$VARS_OUTPUT" >> "$GITHUB_OUTPUT"

      # --------------------------------------------------------------------- #
      # 5️⃣  Generate CHANGELOG entry with structured OpenAI output            #
      # --------------------------------------------------------------------- #
      - name: 🤖 Generate changelog entry
        id: changelog
        uses: ./.github/actions/openai-chat
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          system-path: .github/prompts/changelog.sys.md
          template-path: .github/prompts/changelog.user.md
          schema-path: .github/schema/changelog.schema.json
          output-path: .github/templates/changelog.tmpl.md
          vars: ${{ steps.vars.outputs.template_vars }}
          model: ${{ secrets.OPENAI_MODEL || 'gpt-4o-mini' }}
          temperature: 0.3
          max-tokens: 1200

      # --------------------------------------------------------------------- #
      # 6️⃣  Write / prepend the new entry to CHANGELOG.md                    #
      # --------------------------------------------------------------------- #
      - name: 📝 Update CHANGELOG.md
        env:
          FORMATTED_CONTENT: ${{ steps.changelog.outputs.formatted_content }}
          RAW_CONTENT: ${{ steps.changelog.outputs.content }}
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          export DATE=$(date +%Y-%m-%d)
          ./.github/scripts/release-prepare/update-changelog.sh

      # --------------------------------------------------------------------- #
      # 7️⃣  Commit & push                                                    #
      # --------------------------------------------------------------------- #
      - name: 💾 Commit version + changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git add package.json CHANGELOG.md
          git commit -m "chore(release): v${{ steps.version.outputs.version }} – update changelog" \
            || echo "Nothing to commit"
          git push

      # --------------------------------------------------------------------- #
      # 8️⃣  Summary                                                          #
      # --------------------------------------------------------------------- #
      - name: 🎉 Release prep summary
        run: |
          {
            echo "## 🎉 Release Preparation Complete"
            echo ""
            echo "- **Version:**  `${{ steps.version.outputs.version }}`"
            echo "- **Bump type:** `${{ steps.bump.outputs.type }}`"
            echo "- **CHANGELOG:** updated and committed"
            echo ""
            echo "➡️  Create a PR from **preview ➡️ main** when ready to publish."
          } >> "$GITHUB_STEP_SUMMARY"
